[package]
name = "mieli"
version = "0.1.7"
edition = "2018"
description = "A cli around Meilisearch"
readme = "README.md"
homepage = "https://meilisearch.com/"
documentation = "https://docs.meilisearch.com"
license = "WTFPL"
repository = "https://github.com/irevoire/mieli"
keywords = ["meilisearch", "cli", "search", "bears"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
structopt = "0.3.22"
reqwest = { version = "0.11.4", default-features = false, features = ["rustls-tls", "blocking", "json"] }
termion = "1.5.6"
serde_json = "1.0.66"
indicatif = "0.16.2"
colored_json = "2.1.0"

[profile.release]
opt-level = "z"  # Optimize for size.
lto = true
panic = "abort"
