[package]
name = "mieli"
version = "0.28.2"
edition = "2021"
description = "A cli around Meilisearch"
readme = "README.md"
homepage = "https://meilisearch.com/"
documentation = "https://docs.meilisearch.com"
license = "WTFPL"
repository = "https://github.com/irevoire/mieli"
keywords = ["meilisearch", "cli", "search", "bears"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2"
clap = { version = "3.2.17", features = ["color", "suggestions", "derive", "env"] }
reqwest = { version = "0.11.4", default-features = false, features = ["rustls-tls", "blocking", "json"] }
termion = "1.5.6"
serde_json = { version = "1.0.66", features = ["preserve_order"] }
indicatif = "0.16.2"
inquire = "0.2.1"
colored_json = "2.1.0"
miette = { version = "5.3.0", features = ["fancy"] }
yaup = "0.2.1"
serde = { version = "1.0.143", features = ["serde_derive"] }
serde-cs = "0.2.4"
clap_complete = "3.2.4"
dialoguer = "0.10.2"
meilisearch-sdk = "0.21.2"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }

[profile.release]
opt-level = "z"  # Optimize for size.
lto = true
panic = "abort"
